### ISSUE TITLE
OS X version, libhunspell-1.3.0.dylib is a symbolic link to a relative path.

### ISSUE THREAD

**Issue by Invincibl-e** [copperspice/diamond#1]
In http://download.copperspice.com/diamond/binary/Diamond-1.2.3.dmg, the symbolic link Diamond.app/Contents/Frameworks/libhunspell-1.3.dylib to libhunspell-1.3.0.dylib.
hope you fix it.

**Comment by agserm** [comment]
Thank you for your report.

We have fixed the Diamond build process for OS X. A new version of Diamond will be posted at the end of next week.
