### ISSUE TITLE
Windows Explorer Open With Diamond.exe doesn't have icon

### ISSUE THREAD

**Issue by 3oheicrw** [copperspice/diamond#10]
The familiar diamond icon is missing. It's only with Open With, the Diamond shortcut on Desktop still has icon as normal.

**Comment by bgeller** [comment]
The icon was missing in the upper left corner of Diamond?  

Please describe exactly what you did so we try to repeat this.

**Comment by 3oheicrw** [comment]
> The icon was missing in the upper left corner of Diamond?
> 
> Please describe exactly what you did so we try to repeat this.

Right click on the file -> Open With -> Diamond Editor (no icon).
Right click on the file -> Open With -> Choose default program... -> Browse to Diamond.exe -> Diamond.exe added (no icon)

**Comment by bgeller** [comment]
I was able to open Diamond and the icon in the upper left corner of the application.  Sorry, it is still unclear where it is missing.

**Comment by bgeller** [comment]
A user let us know we were missing the `diamond.rc` file. Adding this file will display the icon you are looking for.  This change will be part of a new Diamond release which is scheduled for this week.
