### ISSUE TITLE
Add File/Clear Recent Files to remove Recent Opened Files list

### ISSUE THREAD

**Issue by 3oheicrw** [copperspice/diamond#13]
Currently no way to do this from the editor. Have to manually edit CS/Diamond Editor/config.json.

**Comment by bgeller** [comment]
This feature is already present in Diamond. Hover the mouse over a file name and then right click the mouse. You will see options to "clear the recent file list" or "remove" the given file name.

**Comment by bgeller** [comment]
Closing since this feature already existed.
