### ISSUE TITLE
Add portable .zip or .7z binaries of the editor

### ISSUE THREAD

**Issue by 3oheicrw** [copperspice/diamond#15]
Currently there is only the setup executable. I wanted to use Diamond as a portable text editor could run completely portable from my usb thumb drive. I think many users would have the same use case as me. Please consider.

**Comment by bgeller** [comment]
We are not using zip files for Windows installation. Packages are under consideration.

If this is something you are interested in maintaining please let us know and we can work with you. Diamond does modify a few registry settings when the program is first launched.

**Comment by 3oheicrw** [comment]
> We are not using zip files for Windows installation. Packages are under consideration.
> 
> If this is something you are interested in maintaining please let us know and we can work with you. Diamond does modify a few registry settings when the program is first launched.

Please add .zip or .7z package of it. I don't understand why CopperSpice and Diamond on Linux are distributed as an archive but on Windows it needs a setup just to be able to use them.

**Comment by bgeller** [comment]
It is not customary to use an installer for Unix platforms. What is actually more common are deb and rpm packages which serve the purpose of an installer. 

The CopperSpice team has selected vcpkg and we are in the process of working with a developer at Microsoft. This will be an awesome addition.

**Comment by bgeller** [comment]
Just following up on this. If you decide to repackage and host zip files please let us know so we can note this on our readme file.
