### ISSUE TITLE
Editor window is larger than the screen itself

### ISSUE THREAD

**Issue by 3oheicrw** [copperspice/diamond#16]
It's only a bit larger. Look at the attachment.

When opened:

![Capture2](https://user-images.githubusercontent.com/93332305/148572902-4da658d7-c83c-4d87-8b65-afeeb9503575.PNG)

Have to click Maximize to make it fit the screen:

![Capture3](https://user-images.githubusercontent.com/93332305/148572973-d2f27193-0936-4d75-823f-66d0a57d1f6b.PNG)

**Comment by bgeller** [comment]
This is not something we have every seen in Diamond. Do you see this same behavior if you run KitchenSink or DoxyPress? 

Can you describe the platform, operating system, your DPI settings, display resolution, etc. Thanks

**Comment by 3oheicrw** [comment]
> This is not something we have every seen in Diamond. Do you see this same behavior if you run KitchenSink or DoxyPress?
> 
> Can you describe the platform, operating system, your DPI settings, display resolution, etc. Thanks

Windows 7 64 bit fully updated. Resolution is 1680x1050 with DPI is 120.
