### ISSUE TITLE
Built-in Dark Theme for the editor

### ISSUE THREAD

**Issue by 3oheicrw** [copperspice/diamond#18]
Not to be confused with Dark Color Scheme which only applies to the text area. The Dark Theme apply to the whole editor. It seems the editor is currently not themeable, isn't it? Should this feature be added in future release?

An editor without Dark Theme and Dark Color Scheme is unthinkable in the modern world (I mean a code editor, as a simple text editor notepad.exe doesn't have dark theme nor dark color scheme, but notepad++ definitely has it, doesn't it?).

It seems for me CopperSpice as the framework is not themeable either. So this would be indeed very difficult.

**Comment by bgeller** [comment]
Diamond is an open source CopperSpice application which respects the system colors. It was not designed to be a  replacement for Notepad and was inspired by the Crimson Editor. Our usage of Diamond is to write source code. 

It is worth noting that CS contains "style sheets" which can be used to alter the appearance of the user interface. There is a mall sample of stylesheets in our KitchenSink demo program. We believe that judging a product as "unthinkable" is rather limiting.  The real question one should ask, is does Diamond solve your requirements. 

I would like to clarify that CopperSpice is not a framework, it is a set of cross platform C++ libraries.
