### ISSUE TITLE
"Display as HTML" crashes on non-html files

### ISSUE THREAD

**Issue by Zbyl** [copperspice/diamond#2]
"Display as HTML" crashes on files that are not HTML (i.e. any boost asio header file).

Additionally session (open tabs) is apparently not saved when new tabs are being open, so after a crash old state of session is restored.

Windows 10, Diamond Version: 1.2.3, Build # 05/01/2017

**Comment by agserm** [comment]
This issue no longer exists because we now use the default external HTML viewer.
