### ISSUE TITLE
Diamond hangs when pushing Close in HTML view

### ISSUE THREAD

**Issue by Zbyl** [copperspice/diamond#3]
Diamond hangs when pushing Close in any HTML view.
Clicking close on any page of Diamond Help causes Diamond to hang.
Same thing happens in "Display as HTML" view.

This is not a crash - the application simply stops reacting to any inputs.

Windows 10, Diamond Version: 1.2.3, Build # 05/01/2017

**Comment by agserm** [comment]
This issue no longer exists because we use the default external HTML viewer.
