### ISSUE TITLE
Add screenshots to readme

### ISSUE THREAD

**Issue by NeroBurner** [copperspice/diamond#5]
please add some screenshots on how diamond looks like. Promote the work you are doing :)

**Comment by NeroBurner** [comment]
example screenshot

![Screenshot_20200213_104043](https://user-images.githubusercontent.com/9076163/74421432-4f69bf00-4e4d-11ea-89e7-6fb1f1ffefc1.png)

**Comment by agserm** [comment]
Screenshots in Markdown are very awkward. We prefer to let users have a look at the program.
