### ISSUE TITLE
CsPrinterDriverCups is expected

### ISSUE THREAD

**Issue by NeroBurner** [copperspice/diamond#7]
CopperSpice is expected to be built with Cups plugin. 

https://github.com/copperspice/diamond/blob/134fc16450b0d4d117094a6bbc56e98f56a6c827/src/CMakeLists.txt#L204

it is not checked if the plugin exists, resulting in the following error at the install target

```
-- Installing: /home/nero/repos/diamond/_install/./platforms/CsGuiXcb1.6.so
CMake Error at src/cmake_install.cmake:105 (file):
  file INSTALL cannot find
  "/home/nero/copperspice/_install/lib/CsPrinterDriverCups1.6.so":
  No such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:42 (include)


Makefile:107: recipe for target 'install' failed
make: *** [install] Error 1
```

copperspice compiled from cs-1.6.1

**Comment by agserm** [comment]
Thanks for catching this. We will verify the prebuilt binaries for our next release of CopperSpice and Diamond which are pending for early next week.
