### ISSUE TITLE
Trouble with UTF-8V encoded file

### ISSUE THREAD

**Issue by ruanjiaxing** [copperspice/diamond#8]
Diamond silently quit when opened such file. The java based jedit has no problem opening it and it showed the file is encoded with utf-8v.

You could grab the FreeBASIC linux tar.gz here: [https://sourceforge.net/projects/fbc/files/](url)

The files troubled are in examples/GUI/IUP. As I recall it's frame.bas.

**Comment by bgeller** [comment]
Diamond supports UTF-8 encoded strings.  We are not aware of a separate encoding called UTF-8V.  We will have a look at the file you mentioned and see what might be happening. 

Can you let us know which version of Diamond you were using. 

Thanks!

**Comment by ruanjiaxing** [comment]
I used the latest version of Diamond compiled with Cs 1.6.2 from your binary package.

**Comment by bgeller** [comment]
The newest version of Diamond is 1.3.4 which was compiled with CS 1.6.3.  Did you use this prebuilt binary?

**Comment by bgeller** [comment]
We downloaded the files in **examples/gui/iup** and all 5 files opened with zero issues. I tested with the prebuilt Diamond binary located on our download page.  Can you verify with this exact version and maybe which line of code is causing your a problem.

**Comment by ruanjiaxing** [comment]
I think I used the previous stable version.

The current version worked fine. I don't know why. I think I would close this issue.
